name: outline_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  macos_window_utils: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
